import { test } from 'node:test';
import assert from 'node:assert/strict';

import { parseReplicaConfig, wikiHost, wikiDatabase } from '../service/replicas.js';

test('parseReplicaConfig reads unquoted user/password', () => {
    const cnf = `[client]\nuser = s12345\npassword = abcDEF123\n`;
    assert.deepEqual(parseReplicaConfig(cnf), { user: 's12345', password: 'abcDEF123' });
});

test('parseReplicaConfig strips matching quotes and handles no-space around =', () => {
    const cnf = `[client]\nuser='s12345'\npassword="abc DEF 123"\n`;
    assert.deepEqual(parseReplicaConfig(cnf), { user: 's12345', password: 'abc DEF 123' });
});

test('parseReplicaConfig ignores comments, blank lines, and the section header', () => {
    const cnf = [
        '; generated by toolsadmin',
        '[client]',
        '',
        '# a comment about the user',
        'user = s12345',
        'password = abcDEF123',
        '',
    ].join('\n');
    assert.deepEqual(parseReplicaConfig(cnf), { user: 's12345', password: 'abcDEF123' });
});

test('parseReplicaConfig throws with a readable message when fields are missing', () => {
    assert.throws(() => parseReplicaConfig('[client]\nuser = only_user\n'), /password/);
    assert.throws(() => parseReplicaConfig(''), /user/);
});

test('parseReplicaConfig does not choke on a value containing an equals sign', () => {
    // Passwords can legitimately contain "=" from base64-ish generators; only
    // the first "=" on the line should split key from value.
    const cnf = `user = s12345\npassword = abc=DEF==123\n`;
    assert.deepEqual(parseReplicaConfig(cnf), { user: 's12345', password: 'abc=DEF==123' });
});

test('wikiHost builds the analytics hostname by default', () => {
    assert.equal(wikiHost('enwiki'), 'enwiki.analytics.db.svc.wikimedia.cloud');
});

test('wikiHost supports the web cluster explicitly', () => {
    assert.equal(wikiHost('enwiki', { cluster: 'web' }), 'enwiki.web.db.svc.wikimedia.cloud');
});

test('wikiHost rejects an unknown cluster or a missing wiki', () => {
    assert.throws(() => wikiHost('enwiki', { cluster: 'nope' }), RangeError);
    assert.throws(() => wikiHost(''), TypeError);
    assert.throws(() => wikiHost(), TypeError);
});

test('wikiDatabase appends the _p suffix', () => {
    assert.equal(wikiDatabase('enwiki'), 'enwiki_p');
    assert.equal(wikiDatabase('frwiki'), 'frwiki_p');
});

test('wikiDatabase requires a wiki name', () => {
    assert.throws(() => wikiDatabase(''), TypeError);
});
